package services

import (
	"bytes"
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf"
	"github.com/vincents-ai/transparenz-server-oss/pkg/models"
	"go.uber.org/zap"
)

// PDFService generates BSI TR-03116 compliance PDF reports.
type PDFService struct {
	logger *zap.Logger
}

// NewPDFService creates a PDFService with the given logger.
func NewPDFService(logger *zap.Logger) *PDFService {
	return &PDFService{logger: logger}
}

func (s *PDFService) GeneratePDF(data models.PDFReportData) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetAutoPageBreak(true, 20)
	pdf.SetMargins(20, 20, 20)

	reportID := data.ReportID
	if reportID == "" {
		reportID = "N/A"
	}

	pdf.SetHeaderFunc(func() {
		pdf.SetFont("Helvetica", "", 8)
		pdf.SetTextColor(128, 128, 128)
		pdf.CellFormat(0, 10, fmt.Sprintf("%s | CONFIDENTIAL", reportID), "", 0, "C", false, 0, "")
		pdf.Ln(5)
	})

	pdf.SetFooterFunc(func() {
		pdf.SetY(-15)
		pdf.SetFont("Helvetica", "", 8)
		pdf.SetTextColor(128, 128, 128)
		pdf.CellFormat(0, 10, fmt.Sprintf("Page %d | Generated by Transparenz Server | %s", pdf.PageNo(), time.Now().Format("2006-01-02")), "", 0, "C", false, 0, "")
	})

	pdf.AddPage()

	pdf.SetFont("Helvetica", "B", 18)
	pdf.SetTextColor(0, 51, 102)
	pdf.CellFormat(0, 15, "BSI TR-03116 Compliance Report", "", 1, "C", false, 0, "")
	pdf.Ln(5)

	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(0, 0, 0)
	pdf.CellFormat(0, 6, fmt.Sprintf("Organization: %s", data.OrgName), "", 1, "L", false, 0, "")
	pdf.CellFormat(0, 6, fmt.Sprintf("Report Date: %s", data.ReportDate), "", 1, "L", false, 0, "")
	pdf.CellFormat(0, 6, fmt.Sprintf("Report ID: %s", data.ReportID), "", 1, "L", false, 0, "")
	pdf.Ln(10)

	for _, section := range data.Sections {
		pdf.SetFont("Helvetica", "B", 14)
		pdf.SetTextColor(0, 51, 102)
		pdf.CellFormat(0, 10, section.Title, "", 1, "L", false, 0, "")
		pdf.Ln(2)

		pdf.SetFont("Helvetica", "", 10)
		pdf.SetTextColor(51, 51, 51)
		for _, line := range splitLines(section.Content) {
			pdf.MultiCell(0, 6, line, "", "L", false)
		}
		pdf.Ln(8)
	}

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, fmt.Errorf("failed to generate PDF: %w", err)
	}
	return buf.Bytes(), nil
}

func splitLines(s string) []string {
	var lines []string
	start := 0
	for i := 0; i < len(s); i++ {
		if s[i] == '\n' {
			lines = append(lines, s[start:i])
			start = i + 1
		}
	}
	if start < len(s) {
		lines = append(lines, s[start:])
	}
	return lines
}
